parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r},p.cache={};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"3igz":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=function(e){if(2===e.length){var r=e.charAt(0),t=e.charAt(1);"nb"===e?e=0:"+"===t?e=r+".5":"-"===t&&(e=Number(r)-.25)}return Number(e)},r=e;exports.default=r;
},{}],"Gr5y":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=t(require("./translateGrade"));function t(e){return e&&e.__esModule?e:{default:e}}var d=function(t){var d=0,l=0;return t.children.length&&[].slice.call(t.childNodes).forEach(function(t){var a,r;if(t.className?(a=t.childNodes[1].title,r=(0,e.default)(t.childNodes[1].textContent)):(a=t.childNodes[2].childNodes[1].title,r=(0,e.default)(t.childNodes[2].childNodes[1].textContent)),!isNaN(r)){var s=Number(a.charAt(a.indexOf("Waga")+6));d+=r*s,l+=s}}),{summedGrades:d,summedScales:l}},l=d;exports.default=l;
},{"./translateGrade":"3igz"}],"lMaA":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=1.65,t=function(t,r,o){for(var s=0,u=t/r,a=t/r;u>e&&(t+o)/(r+o)>e;)u=(t+=o)/(r+=o),t/r>e&&(s++,a=t/r);return{possible1s:s,gpa:a.toFixed(3)}},r=t;exports.default=r;
},{}],"HLYW":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=function(){return[].slice.call(document.querySelectorAll("[class*=line] > td:not(:empty):not([class])")).filter(function(e){return"SPAN"===e.childNodes[0].nodeName})},t=e;exports.default=t;
},{}],"Focm":[function(require,module,exports) {
"use strict";var e=o(require("./summarizeLibrusGradeRow")),n=o(require("./calculatePossible1s")),a=o(require("./findLibrusGradeRows"));function o(e){return e&&e.__esModule?e:{default:e}}(0,a.default)().forEach(function(a){var o=(0,e.default)(a),s=o.summedGrades,t=o.summedScales,r=(0,n.default)(s,t,4),c=(0,n.default)(s,t,3),i=(0,n.default)(s,t,2),l=(0,n.default)(s,t,1),d="Ilość jedynek wagi 4 które możesz otrzymać: ".concat(r.possible1s,"\nPozostanie ci średnia: ").concat(r.gpa,"\n\nIlość jedynek wagi 3 które możesz otrzymać: ").concat(c.possible1s,"\nPozostanie ci średnia: ").concat(c.gpa,"\n\nIlość jedynek wagi 2 które możesz otrzymać: ").concat(i.possible1s,"\nPozostanie ci średnia: ").concat(i.gpa,"\n\nIlość jedynek wagi 1 które możesz otrzymać: ").concat(l.possible1s,"\nPozostanie ci średnia: ").concat(l.gpa),u='\n<span class="grade-box librus-plus__grade-box">\n    <a class="ocena librus-plus__ocena" href="#" title="'.concat(d,'">\n    ').concat(c.possible1s,"\n    </a>\n</span>\n"),p=document.createElement("span");p.innerHTML=u,p.onclick=function(){return alert(d)},a.appendChild(p)});var s="\n.librus-plus__grade-box{\n    background-color:black;\n    color:white;\n    border: 8px solid gold;\n}\n.librus-plus__ocena{\n    color: white !important;\n    font-weight: bold;\n}\n",t=document.createElement("style");t.innerHTML=s,document.head.appendChild(t);
},{"./summarizeLibrusGradeRow":"Gr5y","./calculatePossible1s":"lMaA","./findLibrusGradeRows":"HLYW"}]},{},["Focm"], null)